cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'awscli'
brew 'coreutils'
brew 'direnv'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'fzf'
brew 'git'
brew 'jq'
brew 'libpq', link: true
brew 'mas'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pre-commit'
brew 'pyenv-virtualenv'
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build'
brew 'wget'
brew 'yarn'
cask '1password-cli'
cask '1password'
cask 'google-chrome'
cask 'iterm2'
cask 'rancher'
cask 'slack'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'
